using NUnit.Framework;
using IntegerGenerator;

namespace IntegerGenerator.Tests
{
    [TestFixture]
    public class IntegerGeneratorTestClass
    {
        [Test]
        public static void GenerateValueTestMethod()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public static void GetGeneratorTypeNameTestMethod()
        {
            Assert.Fail("autogenerated");
        }
    }
}