using NUnit.Framework;
using FloatGenerator;

namespace FloatGenerator.Tests
{
    [TestFixture]
    public class FloatGeneratorTestClass
    {
        [Test]
        public static void GenerateValueTestMethod()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public static void GetGeneratorTypeNameTestMethod()
        {
            Assert.Fail("autogenerated");
        }
    }
}