using NUnit.Framework;
using Faker;

namespace Faker.Tests
{
    [TestFixture]
    public class FakerTestClass
    {
        [Test]
        public static void CreateTestMethod()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public static void GenerateValueTestMethod()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public static void ListGeneratorTestMethod()
        {
            Assert.Fail("autogenerated");
        }
    }
}